# mutation{
#   loginUser(login: "functionbucket@gmail.com", password: "D70sDrll26OQo+iArwEeK/3gEqR6wUEzTrsIcDuCMkA="){
#     email,
#     token
#   }
# }

# mutation{
#   logoutToken(token: "d1689a7e-1d43-4799-91b5-0efb675c5419")
# }

query {
  authenticatedUser(token: "d1689a7e-1d43-4799-91b5-0efb675c5419"){
    id,
    firstName,
    lastName,
    login,
    token,
    expirationDate
  }
}