module.exports = {
  "5": "Kief",
  "6": "Flower",
  "7": "Clone",
  "9": "Other Plant Material(stems, leaves, etc) to be processed",
  "10": "Seed",
  "11": "Plant Tissue",
  "12": "Mature Plant",
  "13": "Flower Lot",
  "14": "Other Plant Material Lot",
  "15": "Bubble Hash",
  "16": "Hash",
  "17": "Hydrocarbon Wax",
  "18": "CO2 Hash Oil",
  "19": "Food Grade Solvent Extract",
  "20": "Infused Dairy Butter or Fat in Solid Form",
  "21": "Infused Cooking Oil",
  "22": "Solid Marijuana Infused Edible",
  "23": "Liquid Marijuana Infused Edible",
  "24": "Marijuana Extract for Inhalation",
  "25": "Marijuana Infused Topicals",
  "26": "Sample Jar",
  "27": "Waste",
  "28": "Usable Marijuana",
  "29": "Wet Flower",
  "30": "Marijuana Mix",
  "31": "Marijuana Mix Packaged",
  "32": "Marijuana Mix Infused",
  "33": "Non-Mandatory QA Sample",
  "34": "Capsule",
  "35": "Tincture",
  "36": "Transdermal Patch",
  "37": "Suppository"
};
